version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
        - .:/code
    ports:
      - '6379:6379'
    networks:
      - redis-network

  celery:
    depends_on:
      - redis
      # - mongodb
    build: .
    command: bash start.sh
    expose:
      - '${FLOWER_PORT}'
    ports:
      - '${FLOWER_PORT}:${FLOWER_PORT}'
    volumes:
      - .:/code
    networks:
      - redis-network
    environment:
      LOCAL_HOSTS_REDIS: redis
      DBAAS_SENTINEL_PORT: 6379
      DBAAS_REDIS_HOST: redis://redis:6379/0
networks:
  redis-network: