version: '3'
services:
  redis:
    image: redis:latest
    container_name: redis
    volumes:
        - .:/code
    ports:
      - '6379:6379'
    networks:
      - redis-network

  celery:
    depends_on:
      - redis
      # - mongodb
    build: .
    command: bash start.sh
    expose:
      - '5555'
      - '${FLASK_PORT}'
    ports:
    - "${FLASK_PORT}:${FLASK_PORT}"
    - "5555:5555"
    volumes:
      - .:/code
    networks:
      - redis-network
    environment:
      LOCAL_HOSTS_REDIS: redis
      DBAAS_SENTINEL_PORT: 6379
      DBAAS_REDIS_ENDPOINT: redis://redis:6379/0
      FLOWER_PORT: 5555
networks:
  redis-network:  